// AUTO-SYNCED from ~/bldesy-web/lib/slug.ts by scripts/sync-web-libs.mjs — DO NOT EDIT HERE.
// Change the website original, then run: npm run sync:web

/**
 * URL slug rules — the TypeScript twin of public.slugify() in migration
 * 20260726_profile_slugs.sql. The two MUST stay in lockstep: profile slugs
 * are generated by the DB, but suburb URL segments are slugified here and
 * compared against DB-derived values, so a divergence shows up as spurious
 * 308s or dead category pages.
 *
 * Rules: lowercase → strip accents → drop apostrophes → every remaining
 * non-[a-z0-9] run collapses to "-" → trim hyphens → empty becomes null.
 *
 *   "Harbour City Plumbing & Gas" → "harbour-city-plumbing-gas"
 *   "O'Connor"                    → "oconnor"
 *   "Mount Kuring-gai"            → "mount-kuring-gai"
 */

// NFKD strips combining accents (é, ü…) but not standalone letters that
// Postgres' unaccent() maps to ASCII. Cover the ones that plausibly appear
// in Australian business/suburb names so both sides agree.
const NON_DECOMPOSABLE: Record<string, string> = {
  "ø": "o", // ø
  "æ": "ae", // æ
  "œ": "oe", // œ
  "ß": "ss", // ß
  "đ": "d", // đ
  "ð": "d", // ð
  "þ": "th", // þ
  "ł": "l", // ł
};

/**
 * Decode a raw dynamic-route segment. The new SEO tree is the de-facto
 * catch-all for junk paths, so malformed percent-encoding must land on a
 * cheap null → notFound(), never a thrown URIError.
 */
export function safeDecodeSegment(raw: string): string | null {
  try {
    return decodeURIComponent(raw);
  } catch {
    return null;
  }
}

export function slugify(input: string | null | undefined): string | null {
  if (!input) return null;
  const slug = input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[øæœßđðþł]/g, (c) => NON_DECOMPOSABLE[c] ?? c)
    .replace(/['’`]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || null;
}
